### ISSUE TITLE
RF>IS igate seems to truncate packets at NUL bytes

### ISSUE THREAD

**Issue by hessu** [ohanssen/ArcticTracker#2]
Hi,

I am not entirely sure about this, but it seems like inet_writeFB() and wifi_doCommand () treat a received packet as a C string. This will likely cause packets containing NUL bytes to be truncated. Also, after a NUL byte in a packet, the CRLF line termination might not be sent, depending on how the rest of the system works; this could potentially cause two APRS-IS packets to be concatenated into one packet.

https://github.com/ohanssen/ArcticTracker/blob/master/igate.c#L300
https://github.com/ohanssen/ArcticTracker/blob/master/ui/wifi.c#L265
https://github.com/ohanssen/ArcticTracker/blob/master/ui/wifi.c#L155

Unfortunately packets containing \0 bytes are fairly common, although they are unexpected by many software. For example, all Kenwood TM-D710 D710A/D710E radios with slightly old firmware send them at power-on sometimes. AGWtracker software can send UTF-16 encoded unicode, where every second byte is a NUL when encoding latin characters (all other new APRS software uses UTF-8). Other bugs and packet corruptions happen too.

For the long story:
https://github.com/hessu/aprsc/blob/master/doc/IGATE-HINTS.md#packets-truncated-by-igates-due-to-c-string-handling

**Comment by ohanssen** [comment]
Thansk for the tip. Yes I see this in wifi_doCommand where I use chprintf which easily could be replaced with memcpy. However I am not sure how nul's are handled by LUA and NodeMCU running on the ESP-12.

**Comment by hessu** [comment]
Hi,

LUA as a language should in general be able to handle binary byte sequences just fine. It is commonly used at work to deal with binary file contents.

If you can't get packets through the igate uncorrupted, I would suggest switching to another programming language or hardware platform, and discontinue / shut down igates which are corrupting packets.
